[services.tokenrush-backend]
root = "apps/backend"
build = "pnpm run build"
start = "pnpm run start"

[services.tokenrush-backend.env]
NIXPACKS_PNPM_VERSION = "8.10.0"
NIXPACKS_INSTALL_COMMAND = "pnpm install --frozen-lockfile"

[services.tokenrush-frontend]
root = "apps/frontend"
build = "pnpm run build"
start = "pnpm run preview -- --host 0.0.0.0 --port 4173"

[services.tokenrush-frontend.env]
NIXPACKS_PNPM_VERSION = "8.10.0"
NIXPACKS_INSTALL_COMMAND = "pnpm install --frozen-lockfile"
